'use client';

import { useEffect } from "react";
import type { Language } from "@/lib/translations";

const localized = {
  ca: {
    ui: { eyebrow: "Quadern de laboratori · 2025—2026", title1: "Del cable al", title2: "camp acústic.", intro: "Un arxiu d'electrònica, firmware, interfícies i síntesi. Onze capítols sobre com una col·lecció de proves va acabar definint una família d'instruments.", labNote: "Nota de laboratori", index: "Índex", nextField: "Pròxim camp", coming: "12 · Pròximament", celestialLead: "La recerca següent no és una versió d'Aura. És un instrument FPGA independent basat en un banc massiu de ressonadors i parcials.", celestialBody1: "L'FPGA permet que molts ressonadors evolucionin simultàniament com una estructura física digital.", celestialBody2: "Celestial Field separarà algoritme, arquitectura i interfície per fer audible un camp harmònic que no seria pràctic amb un procés seqüencial.", galleryCta: "Explorar els 58 registres", imageCaption: "Documentació visual del procés" },
    chapters: {
      energia: ["Energia abans que música", "Finals de 2025", "La primera decisió no sona", "Abans d'escriure un seqüenciador calia alimentar diverses intel·ligències sense convertir l'àudio en soroll.", "Les primeres proves amb bateria, reguladors i voltímetre van fixar una disciplina: mesurar abans de simplificar. Separar alimentació, massa i pics de consum evita escriure firmware per compensar problemes elèctrics.", "Si una anomalia pot ser elèctrica, es mesura abans de buscar-la al codi."],
      pulso: ["El temps compartit", "Hivern 2025/26", "El seqüenciador troba un pols", "Una caixa de ritmes distribuïda només existeix si totes les parts coincideixen en el mateix instant.", "BPM, setze passos, mute i volum van començar en pantalles separades. L'arquitectura mestre/esclau concentra l'estat musical en un node i converteix la resta en projeccions sincronitzades. El seqüenciador radial va introduir la idea del patró com a forma.", "Patró, tempo i transport pertanyen al mestre; les interfícies són projeccions sincronitzades."],
      arquitectura: ["De plaques a sistema", "Gener de 2026", "Distribuir per especialitzar", "Quan una placa seqüencia, dibuixa, serveix web i processa àudio, cada funció competeix amb el temps real.", "L'ESP32-S3 queda com a cervell musical, l'ESP32-P4 assumeix la interfície i Daisy Seed es reserva per al DSP. Distribuir també obliga a dissenyar paquets, reconnexió, estats obsolets i diagnòstic.", "L'arquitectura distribuïda aïlla els temps crítics i fa visible cada responsabilitat."],
      audio: ["El camí del senyal", "Gener de 2026", "L'àudio mereix un territori propi", "El so en temps real no admet pauses d'interfície, memòria o xarxa.", "Els mòduls I²S permeten provar entrada, sortida, rellotge i nivells per separat. Daisy Seed aporta latència constant, mentre el P4 es concentra en LVGL i control. Aquesta frontera es mantindrà a Aura.", "En àudio, l'estabilitat temporal és una funció."],
      "lenguaje-visual": ["La màquina s'explica", "Primer trimestre de 2026", "Color, jerarquia i estats llegibles", "La interfície deixa de ser diagnòstic quan permet actuar sense traduir mentalment cada paràmetre.", "El color agrupa veus, confirma estats i redueix passos. Pads grans, transport estable i feedback immediat converteixen la pantalla tàctil en un panell d'instrument provat sobre el maquinari real.", "Una interfície musical es mesura per les decisions que permet prendre sense trencar el flux."],
      grafo: ["Senyal com a estructura", "Primer trimestre de 2026", "Del mesclador al graf d'efectes", "Quan setze veus comparteixen efectes, la ruta importa tant com cada valor.", "El graf fa visible l'ordre entre bitcrusher, distorsió, delay i sortida. Després, FX Lab transforma aquesta comprensió tècnica en controls directes per flange, reverb, fold, crush i phaser.", "La topologia també és un paràmetre musical."],
      web: ["Una segona superfície", "Primavera de 2026", "El navegador entra a l'instrument", "La web no és administració: és una altra manera de tocar la mateixa màquina.", "L'ESP32 crea una xarxa local i comparteix estat amb ordinador, tauleta i telèfon. La UI web accelera el disseny i ofereix pads, seqüenciador, FX, MIDI, SD i escenes completes sense lligar l'instrument a una sola pantalla.", "L'estat musical no pertany a la pantalla que el mostra."],
      gesto: ["Més enllà del panell", "Primavera de 2026", "Provar el gest abans de necessitar-lo", "Algunes branques poden canviar el projecte encara que no arribin al producte.", "El seguiment de mà investiga distància, velocitat, obertura i trajectòria com a controls continus. L'experiment no substitueix els pads, però anticipa el vocabulari espacial de RayDrone i Aura.", "Un prototip també serveix per descartar una interfície i conservar una idea."],
      instrumento: ["Del test a la sessió", "Primavera–estiu de 2026", "La caixa desapareix i queda el gest", "El punt d'inflexió arriba quan es deixa de verificar i es comença a tocar durant hores.", "Pantalles, encoders i llum formen una escena coherent. Les sessions llargues revelen fatiga, latència, estats ambigus i reconnexions. RED808 es consolida com a laboratori d'arquitectura instrumental.", "Un instrument comença on acaba la demo."],
      raydrone: ["Canvi de pregunta", "Estiu de 2026", "Del ritme al traçat acústic", "La recerca passa d'organitzar esdeveniments a preguntar si el so pot emergir de camins.", "RayDrone trasllada el ray tracing al buffer: cada trajectòria acumula i convergeix sobre material capturat. Rust, WebAssembly i AudioWorklet separen l'algoritme del maquinari i permeten estudiar-lo i publicar-lo.", "L'algoritme ha de poder existir sense la màquina."],
      aura: ["L'algoritme torna al cos", "Ara", "Aura: RayDrone + P4", "Després de separar l'algoritme, cal dissenyar l'instrument que realment necessita.", "Aura combina RayDrone i ESP32-P4 en una unitat autònoma. La telemetria de CPU, memòria, latència, bus i errors permet distingir motor, interfície, comunicació i àudio. Hereta les lliçons de RED808 sense ser una caixa de ritmes.", "RayDrone és el comportament. Aura és l'objecte i la interpretació."],
    },
  },
  en: {
    ui: { eyebrow: "Laboratory notebook · 2025—2026", title1: "From wire to", title2: "acoustic field.", intro: "An archive of electronics, firmware, interfaces and synthesis. Eleven chapters on how a collection of tests became a family of instruments.", labNote: "Lab note", index: "Index", nextField: "Next field", coming: "12 · Coming next", celestialLead: "The next investigation is not a version of Aura. It is an independent FPGA instrument built around a massive bank of resonators and partials.", celestialBody1: "FPGA changes the meaning of parallelism by allowing many resonators to evolve simultaneously as a digital physical structure.", celestialBody2: "Celestial Field will separate algorithm, architecture and interface to make an otherwise impractical harmonic field audible.", galleryCta: "Explore all 58 records", imageCaption: "Visual process documentation" },
    chapters: {
      energia: ["Energy before music", "Late 2025", "The first decision makes no sound", "Before writing a sequencer, several independent systems had to be powered without turning audio into noise.", "Early battery, regulator and meter tests established a rule: measure before simplifying. Separating power, grounding and load spikes prevents firmware from being written to compensate for electrical faults.", "If an anomaly might be electrical, measure it before searching the code."],
      pulso: ["Shared time", "Winter 2025/26", "The sequencer finds its pulse", "A distributed drum machine only exists when every part agrees on the same instant.", "BPM, sixteen steps, mute and volume began on separate displays. A master/slave architecture keeps musical state in one node and turns every interface into a synchronized projection. The radial sequencer introduced the pattern as a visual form.", "Pattern, tempo and transport belong to the master; interfaces are synchronized projections."],
      arquitectura: ["From boards to system", "January 2026", "Distribute to specialize", "When one board sequences, draws, serves a web UI and processes audio, every feature competes with real time.", "ESP32-S3 becomes the musical brain, ESP32-P4 handles graphics and Daisy Seed is reserved for DSP. Distribution also means designing packets, reconnection, stale state and diagnostics from the beginning.", "Distributed architecture isolates critical timings and makes responsibilities visible."],
      audio: ["The signal path", "January 2026", "Audio deserves its own territory", "Real-time sound cannot wait for interfaces, memory management or networking.", "I²S modules isolate input, output, clock and levels. Daisy Seed provides constant DSP timing while P4 focuses on LVGL and control. This boundary later becomes part of Aura's architecture.", "In audio, timing stability is a feature."],
      "lenguaje-visual": ["The machine explains itself", "First quarter 2026", "Color, hierarchy and readable states", "An interface stops being a diagnostic screen when it supports action without mental translation.", "Color groups voices, confirms state and reduces navigation. Large pads, stable transport and immediate feedback turn the touchscreen into an instrument panel tested on real hardware.", "A musical interface is measured by the decisions it enables without breaking flow."],
      grafo: ["Signal as structure", "First quarter 2026", "From mixer to effects graph", "When sixteen voices share effects, routing matters as much as every value.", "The graph exposes the order between bitcrusher, distortion, delay and master output. FX Lab then turns that technical understanding into direct controls for flange, reverb, fold, crush and phaser.", "Topology is also a musical parameter."],
      web: ["A second surface", "Spring 2026", "The browser enters the instrument", "The web UI is not administration; it is another way to play the same machine.", "The ESP32 creates a local network and shares state with computer, tablet and phone. The browser accelerates design and offers pads, sequencer, FX, MIDI, SD and scenes without tying the instrument to one display.", "Musical state does not belong to the screen that displays it."],
      gesto: ["Beyond the panel", "Spring 2026", "Testing gesture before it is needed", "A research branch can change the project even when it never becomes the product.", "Hand tracking explores distance, speed, openness and trajectory as continuous controls. It does not replace pads, but it anticipates the spatial vocabulary of RayDrone and Aura.", "A prototype can reject an interface while preserving an idea."],
      instrumento: ["From test to session", "Spring–summer 2026", "The box disappears and gesture remains", "The turning point arrives when testing stops and the machine is played for hours.", "Screens, encoders and lighting become one coherent scene. Long sessions reveal fatigue, latency, ambiguous state and reconnection issues. RED808 becomes a laboratory for instrument architecture.", "An instrument begins where the demo ends."],
      raydrone: ["A different question", "Summer 2026", "From rhythm to acoustic ray tracing", "Research moves from organizing events to asking whether sound can emerge from paths.", "RayDrone maps ray tracing onto the audio buffer: trajectories accumulate and converge over captured material. Rust, WebAssembly and AudioWorklet separate the algorithm from hardware so it can be studied and published.", "The algorithm must be able to exist without the machine."],
      aura: ["The algorithm returns to the body", "Now", "Aura: RayDrone + P4", "Once the algorithm is independent, the next task is designing the instrument it actually needs.", "Aura combines RayDrone and ESP32-P4 in an autonomous unit. CPU, memory, latency, bus and error telemetry distinguish engine, interface, communication and audio. It inherits RED808's lessons without being a drum machine.", "RayDrone is the behavior. Aura is the object and the performance."],
    },
  },
  de: {
    ui: { eyebrow: "Labortagebuch · 2025—2026", title1: "Vom Kabel zum", title2: "akustischen Feld.", intro: "Ein Archiv aus Elektronik, Firmware, Interfaces und Synthese. Elf Kapitel darüber, wie aus Versuchen eine Instrumentenfamilie wurde.", labNote: "Labornotiz", index: "Inhalt", nextField: "Nächstes Feld", coming: "12 · Demnächst", celestialLead: "Die nächste Forschung ist keine Aura-Version, sondern ein eigenständiges FPGA-Instrument mit einer massiven Bank aus Resonatoren und Teiltönen.", celestialBody1: "FPGA ermöglicht vielen Resonatoren, gleichzeitig als digitale physikalische Struktur zu evolvieren.", celestialBody2: "Celestial Field trennt Algorithmus, Architektur und Oberfläche, um ein sonst unpraktisches harmonisches Feld hörbar zu machen.", galleryCta: "Alle 58 Einträge ansehen", imageCaption: "Visuelle Prozessdokumentation" },
    chapters: {
      energia: ["Energie vor Musik", "Ende 2025", "Die erste Entscheidung klingt nicht", "Vor dem Sequencer mussten mehrere Systeme versorgt werden, ohne das Audiosignal zu stören.", "Tests mit Akku, Reglern und Messgerät etablierten eine Regel: erst messen, dann vereinfachen. So wird keine Firmware geschrieben, die eigentlich elektrische Fehler kompensiert.", "Kann eine Störung elektrisch sein, wird sie vor der Codesuche gemessen."],
      pulso: ["Gemeinsame Zeit", "Winter 2025/26", "Der Sequencer findet seinen Puls", "Eine verteilte Drum Machine existiert nur, wenn alle Teile denselben Zeitpunkt teilen.", "BPM, sechzehn Schritte, Mute und Lautstärke begannen auf getrennten Anzeigen. Die Master/Slave-Architektur hält den musikalischen Zustand zentral und synchronisiert alle Oberflächen.", "Pattern, Tempo und Transport gehören dem Master."],
      arquitectura: ["Von Platinen zum System", "Januar 2026", "Verteilen, um zu spezialisieren", "Wenn eine Platine sequenziert, zeichnet, Web ausliefert und Audio verarbeitet, konkurriert alles mit Echtzeit.", "ESP32-S3 wird musikalisches Gehirn, ESP32-P4 übernimmt Grafik und Daisy Seed den DSP. Pakete, Wiederverbindung, veraltete Zustände und Diagnose werden Teil der Architektur.", "Verteilung isoliert kritische Zeitabläufe und macht Verantwortung sichtbar."],
      audio: ["Der Signalweg", "Januar 2026", "Audio braucht eigenes Territorium", "Echtzeitklang kann nicht auf Oberfläche, Speicher oder Netzwerk warten.", "I²S-Module trennen Ein- und Ausgang, Takt und Pegel. Daisy Seed hält die DSP-Zeit konstant, während P4 LVGL und Steuerung übernimmt.", "Zeitliche Stabilität ist bei Audio eine Funktion."],
      "lenguaje-visual": ["Die Maschine erklärt sich", "Erstes Quartal 2026", "Farbe, Hierarchie und lesbare Zustände", "Eine Oberfläche wird zum Instrument, wenn sie Handlungen ohne mentale Übersetzung ermöglicht.", "Farbe gruppiert Stimmen und bestätigt Zustände. Große Pads, stabiler Transport und sofortiges Feedback entstehen durch Tests auf realer Hardware.", "Eine musikalische Oberfläche schützt den Spielfluss."],
      grafo: ["Signal als Struktur", "Erstes Quartal 2026", "Vom Mixer zum Effektgraphen", "Bei sechzehn Stimmen ist Routing ebenso wichtig wie jeder Parameter.", "Der Graph zeigt Bitcrusher, Distortion, Delay und Ausgang. FX Lab übersetzt dieses Verständnis in direkte Regler für Flange, Reverb, Fold, Crush und Phaser.", "Topologie ist ein musikalischer Parameter."],
      web: ["Eine zweite Oberfläche", "Frühjahr 2026", "Der Browser wird Teil des Instruments", "Die Weboberfläche ist keine Verwaltung, sondern eine weitere Spielweise.", "Das ESP32-Netz teilt Zustand mit Rechner, Tablet und Telefon. Pads, Sequencer, FX, MIDI, SD und Szenen bleiben unabhängig von einem einzelnen Display.", "Der musikalische Zustand gehört nicht dem Bildschirm."],
      gesto: ["Jenseits des Panels", "Frühjahr 2026", "Gesten erproben, bevor sie nötig sind", "Auch ein verworfener Forschungszweig kann das Instrument verändern.", "Handtracking untersucht Abstand, Geschwindigkeit, Öffnung und Bahn als kontinuierliche Steuerung und bereitet das räumliche Vokabular von RayDrone und Aura vor.", "Ein Prototyp kann eine Oberfläche verwerfen und eine Idee behalten."],
      instrumento: ["Vom Test zur Session", "Frühjahr–Sommer 2026", "Die Box verschwindet, die Geste bleibt", "Der Wendepunkt kommt, wenn stundenlang gespielt statt nur geprüft wird.", "Displays, Encoder und Licht werden zu einer Szene. Lange Sessions zeigen Ermüdung, Latenz und Verbindungsprobleme. RED808 wird zum Labor für Instrumentenarchitektur.", "Ein Instrument beginnt dort, wo die Demo endet."],
      raydrone: ["Eine neue Frage", "Sommer 2026", "Vom Rhythmus zum akustischen Raytracing", "Die Forschung fragt nun, ob Klang wie ein Bild aus Pfaden entstehen kann.", "RayDrone überträgt Raytracing auf den Audiopuffer. Rust, WebAssembly und AudioWorklet trennen den Algorithmus von der Hardware und machen ihn untersuchbar und publizierbar.", "Der Algorithmus muss ohne Maschine existieren können."],
      aura: ["Der Algorithmus kehrt zum Körper zurück", "Jetzt", "Aura: RayDrone + P4", "Nach der Trennung des Algorithmus folgt das Instrument, das er wirklich braucht.", "Aura verbindet RayDrone und ESP32-P4. Telemetrie für CPU, Speicher, Latenz, Bus und Fehler trennt Engine, Oberfläche, Kommunikation und Audio.", "RayDrone ist das Verhalten. Aura ist Objekt und Aufführung."],
    },
  },
  fr: {
    ui: { eyebrow: "Carnet de laboratoire · 2025—2026", title1: "Du câble au", title2: "champ acoustique.", intro: "Une archive d'électronique, de firmware, d'interfaces et de synthèse. Onze chapitres sur la naissance d'une famille d'instruments.", labNote: "Note de laboratoire", index: "Sommaire", nextField: "Champ suivant", coming: "12 · Prochainement", celestialLead: "La prochaine recherche n'est pas une version d'Aura, mais un instrument FPGA indépendant fondé sur une banque massive de résonateurs et de partiels.", celestialBody1: "Le FPGA permet à de nombreux résonateurs d'évoluer simultanément comme une structure physique numérique.", celestialBody2: "Celestial Field séparera algorithme, architecture et interface pour rendre audible un champ harmonique autrement impraticable.", galleryCta: "Explorer les 58 traces", imageCaption: "Documentation visuelle du processus" },
    chapters: {
      energia: ["L'énergie avant la musique", "Fin 2025", "La première décision ne produit aucun son", "Avant le séquenceur, il fallait alimenter plusieurs systèmes sans transformer l'audio en bruit.", "Les essais de batterie, régulateurs et mesure ont fixé une règle : mesurer avant de simplifier. On évite ainsi d'écrire du firmware pour masquer un défaut électrique.", "Si une anomalie peut être électrique, on la mesure avant de chercher dans le code."],
      pulso: ["Le temps partagé", "Hiver 2025/26", "Le séquenceur trouve son pouls", "Une boîte à rythmes distribuée n'existe que si toutes ses parties partagent le même instant.", "BPM, seize pas, mute et volume commencent sur des écrans distincts. L'architecture maître/esclave centralise l'état musical et synchronise chaque surface.", "Pattern, tempo et transport appartiennent au maître."],
      arquitectura: ["Des cartes au système", "Janvier 2026", "Distribuer pour spécialiser", "Quand une carte séquence, dessine, sert le web et traite l'audio, tout rivalise avec le temps réel.", "ESP32-S3 devient le cerveau musical, ESP32-P4 gère l'interface et Daisy Seed le DSP. Paquets, reconnexion, états périmés et diagnostic font partie de l'architecture.", "La distribution isole les temps critiques et clarifie les responsabilités."],
      audio: ["Le chemin du signal", "Janvier 2026", "L'audio mérite son propre territoire", "Le son temps réel ne peut attendre l'interface, la mémoire ou le réseau.", "Les modules I²S isolent entrée, sortie, horloge et niveaux. Daisy Seed garantit le rythme du DSP tandis que P4 se consacre à LVGL et au contrôle.", "En audio, la stabilité temporelle est une fonction."],
      "lenguaje-visual": ["La machine s'explique", "Premier trimestre 2026", "Couleur, hiérarchie et états lisibles", "L'interface devient instrument lorsqu'elle permet d'agir sans traduction mentale.", "La couleur regroupe les voix et confirme les états. Grands pads, transport stable et retour immédiat sont validés sur le matériel réel.", "Une interface musicale protège le flux de jeu."],
      grafo: ["Le signal comme structure", "Premier trimestre 2026", "Du mixeur au graphe d'effets", "Avec seize voix, le routage compte autant que chaque valeur.", "Le graphe rend visibles bitcrusher, distorsion, delay et sortie. FX Lab transforme ensuite cette compréhension en commandes directes.", "La topologie est aussi un paramètre musical."],
      web: ["Une seconde surface", "Printemps 2026", "Le navigateur entre dans l'instrument", "L'interface web n'administre pas la machine : elle permet de la jouer autrement.", "Le réseau local ESP32 partage l'état avec ordinateur, tablette et téléphone. Pads, séquenceur, FX, MIDI, SD et scènes ne dépendent plus d'un seul écran.", "L'état musical n'appartient pas à l'écran qui l'affiche."],
      gesto: ["Au-delà du panneau", "Printemps 2026", "Explorer le geste avant d'en avoir besoin", "Une branche abandonnée peut tout de même transformer le projet.", "Le suivi de main explore distance, vitesse, ouverture et trajectoire comme contrôles continus et annonce le vocabulaire spatial de RayDrone et Aura.", "Un prototype peut écarter une interface tout en conservant une idée."],
      instrumento: ["Du test à la session", "Printemps–été 2026", "La boîte disparaît, le geste reste", "Le basculement arrive lorsque l'on joue pendant des heures au lieu de seulement vérifier.", "Écrans, encodeurs et lumière forment une scène. Les longues sessions révèlent fatigue, latence et reconnexions. RED808 devient un laboratoire d'architecture instrumentale.", "Un instrument commence là où la démo s'arrête."],
      raydrone: ["Changer de question", "Été 2026", "Du rythme au lancer de rayons acoustique", "La recherche demande maintenant si un son peut émerger de chemins comme une image.", "RayDrone applique le ray tracing au buffer audio. Rust, WebAssembly et AudioWorklet séparent l'algorithme du hardware afin de l'étudier et de le publier.", "L'algorithme doit pouvoir exister sans la machine."],
      aura: ["L'algorithme revient au corps", "Maintenant", "Aura : RayDrone + P4", "Une fois l'algorithme séparé, il faut concevoir l'instrument dont il a besoin.", "Aura réunit RayDrone et ESP32-P4. La télémétrie CPU, mémoire, latence, bus et erreurs distingue moteur, interface, communication et audio.", "RayDrone est le comportement. Aura est l'objet et l'interprétation."],
    },
  },
} as const;

export function BlogLocaleSync({ language }: { language: Language }) {

  useEffect(() => {
    const translation = language === "es" ? null : localized[language];
    document.querySelectorAll<HTMLElement>("[data-blog-ui]").forEach((el) => {
      el.dataset.originalText ??= el.textContent || "";
      const key = el.dataset.blogUi as keyof (typeof localized.ca.ui);
      el.textContent = translation ? translation.ui[key] : el.dataset.originalText;
    });
    document.querySelectorAll<HTMLElement>("[data-blog-chapter]").forEach((section) => {
      const id = section.dataset.blogChapter as keyof (typeof localized.ca.chapters);
      const values = translation ? translation.chapters[id] as readonly string[] : null;
      const roles = ["kicker", "date", "title", "lead", "body", "note"] as const;
      roles.forEach((role, index) => {
        const el = section.querySelector<HTMLElement>(`[data-role='${role}']`);
        if (!el) return;
        el.dataset.originalHtml ??= el.innerHTML;
        el.innerHTML = values ? (role === "body" ? `<p>${values[index]}</p>` : values[index]) : el.dataset.originalHtml;
      });
      const tocLabel = document.querySelector<HTMLElement>(`a[href='#${id}'] span:last-child`);
      if (tocLabel) {
        tocLabel.dataset.originalText ??= tocLabel.textContent || "";
        tocLabel.textContent = values ? values[0] : tocLabel.dataset.originalText;
      }
      section.querySelectorAll<HTMLElement>("figcaption").forEach((caption, index) => {
        caption.dataset.originalText ??= caption.textContent || "";
        caption.textContent = translation ? `${translation.ui.imageCaption} · ${index + 1}` : caption.dataset.originalText;
      });
    });
  }, [language]);
  return null;
}
