'use client';

import { ArrowUpRight, Headphones, Music2, Radio, Users } from "lucide-react";
import { useLanguage } from "@/lib/language-context";
import Image from "next/image";

const copy = {
  es: { eyebrow: "Escucha compartida", title: "Music & Friends", intro: "La tecnología también se construye escuchando. Este espacio reúne música de amigos y artistas cercanos al laboratorio: trabajos para descubrir con tiempo, auriculares y curiosidad.", growing: "Una colección abierta", growingText: "Iremos añadiendo nuevas voces, sesiones y experimentos. Sin rankings ni algoritmos: solo música que merece circular.", listen: "Escuchar en", discover: "Descubrir", noeron: "Experimento privado · 85 BPM · C major", lima: "Artista · catálogo completo", manel: "Productor y selector · perfil completo", none: "DJ y productor de Lloret de Mar, descubre su vocación a los ocho años a través de los Max Mix, los megamixes y la cultura musical que atravesaba su ciudad. Pionero del scratch y dinamizador de la electrónica en la Costa Brava desde mediados de los noventa, en 2003 encuentra en el minimal-techno una influencia decisiva. Hoy cruza música experimental, hip-hop y pulsión psico-minimalista en una investigación sonora abstracta y melancólica; como DJ puede viajar de los paisajes más cálidos a las psicofonías más insólitas.", replicante: "Electrónica mutante · perfil completo", encounters: "De las ventanas de Zoom a Sa Caleta", encountersText: "Primero disfrutamos de sus sesiones a distancia. Este año por fin coincidimos en persona en ON·OFF y la experiencia fue increíble: música, conversación y muy buen rollo. Bona gent!", francesc: "DJ y cofundador de Inkiet Lloret, la asociación que hace posible ON·OFF y abre espacio a la electrónica y la cultura alternativa local.", nuria: "DJ, productora y fundadora de BlueCube Records. Más de dos décadas llevando un techno hipnótico, elegante y lleno de alma por la escena internacional." },
  ca: { eyebrow: "Escolta compartida", title: "Music & Friends", intro: "La tecnologia també es construeix escoltant. Aquest espai reuneix música d'amics i artistes propers al laboratori: treballs per descobrir amb temps, auriculars i curiositat.", growing: "Una col·lecció oberta", growingText: "Hi anirem afegint noves veus, sessions i experiments. Sense rànquings ni algoritmes: només música que mereix circular.", listen: "Escoltar a", discover: "Descobrir", noeron: "Experiment privat · 85 BPM · Do major", lima: "Artista · catàleg complet", manel: "Productor i selector · perfil complet", none: "DJ i productor de Lloret de Mar, descobreix la seva vocació als vuit anys a través dels Max Mix, els megamixes i la cultura musical que travessava la seva vila. Pioner de l'scratch i dinamitzador de l'electrònica a la Costa Brava des de mitjans dels noranta, el 2003 troba en el minimal-techno una influència decisiva. Avui creua música experimental, hip-hop i pulsió psico-minimalista en una recerca sonora abstracta i melancòlica; com a DJ pot viatjar dels paisatges més càlids a les psicofonies més insòlites.", replicante: "Electrònica mutant · perfil complet", encounters: "De les finestres de Zoom a Sa Caleta", encountersText: "Primer vam gaudir de les seves sessions a distància. Aquest any, per fi, vam coincidir en persona a l'ON·OFF i l'experiència va ser increïble: música, conversa i molt bon rotllo. Bona gent!", francesc: "DJ i cofundador d'Inkiet Lloret, l'associació que fa possible l'ON·OFF i obre espai a l'electrònica i la cultura alternativa local.", nuria: "DJ, productora i fundadora de BlueCube Records. Més de dues dècades portant un techno hipnòtic, elegant i ple d'ànima per l'escena internacional." },
  en: { eyebrow: "Shared listening", title: "Music & Friends", intro: "Technology is also built by listening. This space brings together music by friends and artists close to the lab: work to discover with time, headphones and curiosity.", growing: "An open collection", growingText: "More voices, sessions and experiments will be added over time. No rankings or algorithms—just music worth sharing.", listen: "Listen on", discover: "Discover", noeron: "Private experiment · 85 BPM · C major", lima: "Artist · full catalogue", manel: "Producer and selector · full profile", none: "A DJ and producer from Lloret de Mar, he discovered his calling at eight through Max Mix, megamixes and the musical culture flowing through his hometown. A scratch pioneer and driving force for electronic music on the Costa Brava since the mid-nineties, he found a defining influence in minimal techno in 2003. Today he blends experimental music, hip-hop and a psycho-minimalist pulse in abstract, melancholic sound research; as a DJ, he can travel from the warmest landscapes to the strangest psychophonies.", replicante: "Mutant electronics · full profile", encounters: "From Zoom windows to Sa Caleta", encountersText: "We first enjoyed their sessions from afar. This year we finally met in person at ON·OFF, and it was an incredible experience: music, conversation and wonderful energy. Bona gent!", francesc: "DJ and co-founder of Inkiet Lloret, the association behind ON·OFF that creates space for electronic music and local alternative culture.", nuria: "DJ, producer and founder of BlueCube Records. Over two decades bringing hypnotic, elegant and soulful techno to the international scene." },
  de: { eyebrow: "Gemeinsam hören", title: "Music & Friends", intro: "Technologie entsteht auch durch Zuhören. Dieser Raum versammelt Musik von Freunden und Künstlern aus dem Umfeld des Labors – zum Entdecken mit Zeit, Kopfhörern und Neugier.", growing: "Eine offene Sammlung", growingText: "Weitere Stimmen, Sessions und Experimente kommen dazu. Keine Rankings, keine Algorithmen – nur Musik, die gehört werden sollte.", listen: "Anhören auf", discover: "Entdecken", noeron: "Privates Experiment · 85 BPM · C-Dur", lima: "Künstler · vollständiger Katalog", manel: "Produzent und Selector · vollständiges Profil", none: "Der DJ und Produzent aus Lloret de Mar entdeckte seine Leidenschaft mit acht Jahren durch Max Mix, Megamixes und die Musikkultur seiner Heimatstadt. Seit Mitte der Neunziger ist er Scratch-Pionier und Impulsgeber der elektronischen Szene an der Costa Brava; 2003 wurde Minimal Techno zu einem prägenden Einfluss. Heute verbindet er experimentelle Musik, Hip-Hop und einen psycho-minimalistischen Puls zu abstrakter, melancholischer Klangforschung – als DJ führt er von warmen Klanglandschaften bis zu den ungewöhnlichsten Psychophonien.", replicante: "Mutierte Elektronik · vollständiges Profil", encounters: "Von Zoom-Fenstern nach Sa Caleta", encountersText: "Zuerst erlebten wir ihre Sessions aus der Ferne. Dieses Jahr trafen wir uns endlich persönlich beim ON·OFF – eine unglaubliche Erfahrung voller Musik, Gespräche und guter Energie. Bona gent!", francesc: "DJ und Mitgründer von Inkiet Lloret, dem Verein hinter ON·OFF, der Raum für elektronische Musik und lokale Alternativkultur schafft.", nuria: "DJ, Produzentin und Gründerin von BlueCube Records. Seit über zwei Jahrzehnten bringt sie hypnotischen, eleganten und beseelten Techno auf internationale Bühnen." },
  fr: { eyebrow: "Écoute partagée", title: "Music & Friends", intro: "La technologie se construit aussi en écoutant. Cet espace rassemble la musique d'amis et d'artistes proches du laboratoire, à découvrir avec du temps, un casque et de la curiosité.", growing: "Une collection ouverte", growingText: "De nouvelles voix, sessions et expériences viendront s'ajouter. Sans classement ni algorithme : seulement de la musique qui mérite de circuler.", listen: "Écouter sur", discover: "Découvrir", noeron: "Expérience privée · 85 BPM · Do majeur", lima: "Artiste · catalogue complet", manel: "Producteur et selector · profil complet", none: "DJ et producteur originaire de Lloret de Mar, il découvre sa vocation à huit ans grâce aux Max Mix, aux mégamixes et à la culture musicale qui traverse sa ville. Pionnier du scratch et moteur de la scène électronique de la Costa Brava depuis le milieu des années 1990, il trouve en 2003 une influence décisive dans la minimal techno. Aujourd'hui, il croise musique expérimentale, hip-hop et pulsation psycho-minimaliste dans une recherche sonore abstraite et mélancolique ; comme DJ, il voyage des paysages les plus chaleureux aux psychophonies les plus insolites.", replicante: "Électronique mutante · profil complet", encounters: "Des fenêtres Zoom à Sa Caleta", encountersText: "Nous avons d'abord profité de leurs sessions à distance. Cette année, nous nous sommes enfin rencontrés à ON·OFF : une expérience incroyable, entre musique, conversations et très belles ondes. Bona gent !", francesc: "DJ et cofondateur d'Inkiet Lloret, l'association derrière ON·OFF qui ouvre un espace à la musique électronique et à la culture alternative locale.", nuria: "DJ, productrice et fondatrice de BlueCube Records. Plus de vingt ans de techno hypnotique, élégante et vibrante sur la scène internationale." },
} as const;

const tilloCopy = {
  es: "Pionero del turntablism, fundador de Skratch Comando y uno de los DJs más respetados de la escena hip-hop española. Técnica, humor y una vida entera haciendo magia con el vinilo.",
  ca: "Pioner del turntablism, fundador de Skratch Comando i un dels DJs més respectats de l'escena hip-hop espanyola. Tècnica, humor i tota una vida fent màgia amb el vinil.",
  en: "A turntablism pioneer, founder of Skratch Comando and one of the most respected DJs in Spain's hip-hop scene. Technique, humour and a lifetime of vinyl magic.",
  de: "Turntablism-Pionier, Gründer von Skratch Comando und einer der angesehensten DJs der spanischen Hip-Hop-Szene. Technik, Humor und ein Leben voller Vinyl-Magie.",
  fr: "Pionnier du turntablism, fondateur de Skratch Comando et l'un des DJs les plus respectés de la scène hip-hop espagnole. Technique, humour et toute une vie de magie sur vinyle.",
} as const;

export function MusicFriends() {
  const { language } = useLanguage();
  const t = copy[language];
  return <article className="pt-32 pb-24 px-4 overflow-hidden"><div className="max-w-7xl mx-auto">
    <header className="mb-14 md:mb-20"><div className="flex gap-3 text-primary mb-6"><Headphones /><Users /><Music2 /></div><p className="text-xs uppercase tracking-[.22em] text-primary font-semibold mb-4">{t.eyebrow}</p><h1 className="font-display text-5xl md:text-7xl lg:text-8xl font-bold tracking-tighter mb-7">{t.title}</h1><p className="max-w-3xl text-lg md:text-2xl text-muted-foreground leading-relaxed">{t.intro}</p></header>

    <div className="grid lg:grid-cols-2 gap-6 mb-8">
      <section className="rounded-3xl border border-orange-500/20 bg-card/30 overflow-hidden"><div className="p-6 md:p-8 flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-orange-400 mb-2">SoundCloud</p><h2 className="font-display text-3xl font-bold">Noeron</h2><p className="text-sm text-muted-foreground mt-2">{t.noeron}</p></div><Radio className="text-orange-400" /></div><iframe title="Noeron - Xperiments [85 Cmaj]" width="100%" height="400" scrolling="no" frameBorder="0" allow="autoplay; encrypted-media" loading="lazy" src="https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F2131955805&show_artwork=true&secret_token=s-pXszaWe47eR" /><a href="https://soundcloud.com/noerondj/noeron-xperiments-85-cmaj/s-pXszaWe47eR" target="_blank" rel="noopener noreferrer" className="m-6 md:m-8 mt-5 inline-flex items-center gap-2 text-sm font-semibold text-orange-400">{t.listen} SoundCloud <ArrowUpRight size={15} /></a></section>
      <section className="rounded-3xl border border-emerald-500/20 bg-card/30 overflow-hidden"><div className="p-6 md:p-8 flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-emerald-400 mb-2">Spotify</p><h2 className="font-display text-3xl font-bold">Limabeatz</h2><p className="text-sm text-muted-foreground mt-2">{t.lima}</p></div><Headphones className="text-emerald-400" /></div><div className="px-4 md:px-6"><iframe title="Limabeatz on Spotify" className="w-full rounded-xl" height="352" frameBorder="0" allowFullScreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" src="https://open.spotify.com/embed/artist/4YfPlncfssK9STwd3lroil?utm_source=generator" /></div><a href="https://open.spotify.com/intl-es/artist/4YfPlncfssK9STwd3lroil" target="_blank" rel="noopener noreferrer" className="m-6 md:m-8 mt-5 inline-flex items-center gap-2 text-sm font-semibold text-emerald-400">{t.listen} Spotify <ArrowUpRight size={15} /></a></section>
    </div>

    <section className="rounded-3xl border border-rose-500/20 bg-gradient-to-br from-rose-500/[.08] via-card/40 to-primary/[.06] overflow-hidden mb-8"><div className="p-7 md:p-12 border-b border-white/10"><p className="text-xs uppercase tracking-[.2em] text-rose-400 mb-4">ON·OFF · Music connects</p><h2 className="font-display text-3xl md:text-5xl font-bold max-w-3xl">{t.encounters}</h2><p className="mt-5 max-w-3xl text-lg text-muted-foreground leading-relaxed">{t.encountersText}</p></div><div className="grid md:grid-cols-2"><div className="md:border-r border-white/10"><div className="relative aspect-[16/9] overflow-hidden"><Image src="/music-friends/francesc-ferrer-inkiet.png" alt="Francesc Ferrer punxant en directe" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover object-center" /></div><div className="p-7 md:p-10"><p className="text-xs uppercase tracking-widest text-rose-400 mb-2">Inkiet Lloret · ON·OFF</p><h3 className="font-display text-3xl font-bold">Francesc Ferrer</h3><p className="mt-4 text-muted-foreground leading-relaxed">{t.francesc}</p><a href="https://onoffmusicfestival.com/" target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-rose-400">{t.discover} ON·OFF <ArrowUpRight size={15} /></a></div></div><div><div className="relative aspect-[16/9] overflow-hidden"><Image src="/music-friends/nuria-ghia.jpg" alt="Núria Ghia" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div className="p-7 md:p-10"><p className="text-xs uppercase tracking-widest text-rose-400 mb-2">BlueCube Records · Techno</p><h3 className="font-display text-3xl font-bold">Núria Ghia</h3><p className="mt-4 text-muted-foreground leading-relaxed">{t.nuria}</p><iframe title="Núria Ghia on SoundCloud" width="100%" height="166" scrolling="no" frameBorder="0" allow="autoplay; encrypted-media" loading="lazy" className="mt-6 rounded-xl" src="https://w.soundcloud.com/player/?url=https%3A%2F%2Fsoundcloud.com%2Fnuriaghia&color=%23fb7185&auto_play=false&show_artwork=true&show_user=true" /><div className="mt-7 flex flex-wrap gap-5"><a href="https://soundcloud.com/nuriaghia" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-rose-400">{t.listen} SoundCloud <ArrowUpRight size={15} /></a><a href="https://nuriaghia.com/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-rose-400">{t.discover} Núria Ghia <ArrowUpRight size={15} /></a></div></div></div></div></section>

    <section className="rounded-3xl border border-sky-500/20 bg-card/30 overflow-hidden mb-8"><div className="grid lg:grid-cols-[.7fr_1.3fr] items-center"><div className="p-7 md:p-10"><p className="text-xs uppercase tracking-widest text-sky-400 mb-2">SoundCloud</p><h2 className="font-display text-3xl md:text-4xl font-bold">Manel Alsina</h2><p className="text-muted-foreground mt-3 mb-6">{t.manel}</p><a href="https://soundcloud.com/manelalsina" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-sky-400">{t.listen} SoundCloud <ArrowUpRight size={15} /></a></div><iframe title="Manel Alsina on SoundCloud" width="100%" height="450" scrolling="no" frameBorder="0" allow="autoplay; encrypted-media" loading="lazy" src="https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Fusers%2F6441252&show_artwork=true" /></div></section>

    <div className="grid lg:grid-cols-2 gap-6 mb-8">
      <section className="rounded-3xl border border-fuchsia-500/20 bg-card/30 overflow-hidden flex flex-col"><div className="relative aspect-[16/9] overflow-hidden"><Image src="/music-friends/djnone.jpeg" alt="None actuant en directe" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-left" /></div><div className="p-7 md:p-9"><p className="text-xs uppercase tracking-widest text-fuchsia-400 mb-3">ElectroniKa · Lloret de Mar</p><h2 className="font-display text-4xl font-bold">None</h2><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full border border-fuchsia-500/25 bg-fuchsia-500/[.06] px-3 py-1 text-xs font-semibold tracking-wide text-fuchsia-300">ANDROPUNK RECORDS</span></div><p className="text-muted-foreground mt-6 leading-relaxed">{t.none}</p><iframe title="IVTGLTCH (closed cicles) by None" className="w-full mt-6 rounded-xl border-0" height="340" loading="lazy" src="https://bandcamp.com/EmbeddedPlayer/album=4205372340/size=large/bgcol=111111/linkcol=f0abfc/artwork=small/transparent=true/" seamless /><div className="pt-7 flex flex-wrap gap-5"><a href="https://andropunkrecords.bandcamp.com/album/ivtgltch-closed-cicles" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-fuchsia-400">{t.listen} IVTGLTCH · Bandcamp <ArrowUpRight size={15} /></a><a href="https://modulardaybarcelona.org/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-fuchsia-400">{t.discover} Pauk + None <ArrowUpRight size={15} /></a></div></div></section>
      <section className="rounded-3xl border border-violet-500/20 bg-card/30 overflow-hidden"><div className="p-7 md:p-9"><p className="text-xs uppercase tracking-widest text-violet-400 mb-2">SoundCloud</p><h2 className="font-display text-4xl font-bold">Replicante Norman</h2><p className="text-muted-foreground mt-3">{t.replicante}</p></div><iframe title="Replicante Norman on SoundCloud" width="100%" height="300" scrolling="no" frameBorder="0" allow="autoplay; encrypted-media" loading="lazy" src="https://w.soundcloud.com/player/?url=https%3A%2F%2Fsoundcloud.com%2Freplicantenorman&color=%238b5cf6&auto_play=false&show_artwork=true&show_user=true" /><a href="https://soundcloud.com/replicantenorman" target="_blank" rel="noopener noreferrer" className="m-7 md:m-9 mt-5 inline-flex items-center gap-2 text-sm font-semibold text-violet-400">{t.listen} SoundCloud <ArrowUpRight size={15} /></a></section>
    </div>

    <section className="rounded-3xl border border-amber-500/20 bg-card/30 overflow-hidden mb-8"><div className="grid lg:grid-cols-[.72fr_1.28fr] items-stretch"><div className="p-7 md:p-10 flex flex-col"><p className="text-xs uppercase tracking-widest text-amber-400 mb-2">Turntablism · Skratch Comando</p><h2 className="font-display text-4xl font-bold">DJ Tillo</h2><p className="text-muted-foreground mt-5 leading-relaxed">{tilloCopy[language]}</p><a href="https://soundcloud.com/dj-tillo" target="_blank" rel="noopener noreferrer" className="mt-auto pt-8 inline-flex items-center gap-2 text-sm font-semibold text-amber-400">{t.listen} SoundCloud <ArrowUpRight size={15} /></a></div><iframe title="DJ Tillo on SoundCloud" width="100%" height="450" scrolling="no" frameBorder="0" allow="autoplay; encrypted-media" loading="lazy" src="https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fsoundcloud.com%2Fdj-tillo&color=%23f59e0b&auto_play=false&show_artwork=true&show_user=true" /></div></section>

    <div className="rounded-3xl border border-dashed border-primary/30 bg-primary/[.04] p-8 md:p-12 text-center"><Users className="mx-auto text-primary mb-5" size={30} /><h2 className="font-display text-3xl font-bold mb-4">{t.growing}</h2><p className="max-w-2xl mx-auto text-muted-foreground leading-relaxed">{t.growingText}</p></div>
  </div></article>;
}
