'use client';

import Link from "next/link";
import { ArrowRight, ArrowUpRight, BrainCircuit, CloudOff, Layers3 } from "lucide-react";
import { useLanguage } from "@/lib/language-context";

const copy = {
  es: { back: "Volver al portfolio", badge: "IA local · Separación de audio · Demucs", intro: "Una plataforma para separar, escuchar y gestionar stems musicales con inteligencia artificial ejecutada completamente en local.", demo: "Demo de openStems", demoText: "La demostración muestra el flujo real del proyecto: cargar material, ejecutar la separación y trabajar con las pistas resultantes desde una única interfaz.", local: "Privacidad por diseño", localText: "El audio no necesita abandonar el equipo. El procesamiento local evita depender de servicios externos y mantiene el material bajo control.", model: "Separación con Demucs", modelText: "El motor utiliza separación de fuentes musicales para obtener voces, batería, bajo y otros componentes editables.", workflow: "Del archivo a los stems", workflowText: "openStems reúne preparación, separación, preescucha y gestión en un flujo pensado para músicos, productores e investigación.", youtube: "Ver directamente en YouTube", next: "Explorar más proyectos" },
  ca: { back: "Tornar al portfolio", badge: "IA local · Separació d'àudio · Demucs", intro: "Una plataforma per separar, escoltar i gestionar stems musicals amb intel·ligència artificial executada completament en local.", demo: "Demo d'openStems", demoText: "La demostració mostra el flux real: carregar material, executar la separació i treballar amb les pistes resultants des d'una sola interfície.", local: "Privacitat per disseny", localText: "L'àudio no ha de sortir de l'equip. El processament local evita serveis externs i manté el material sota control.", model: "Separació amb Demucs", modelText: "El motor utilitza separació de fonts musicals per obtenir veus, bateria, baix i altres components editables.", workflow: "De l'arxiu als stems", workflowText: "openStems reuneix preparació, separació, preescolta i gestió en un flux per a músics, productors i recerca.", youtube: "Veure directament a YouTube", next: "Explorar més projectes" },
  en: { back: "Back to portfolio", badge: "Local AI · Audio separation · Demucs", intro: "A platform for separating, auditioning and managing musical stems with AI running entirely on the local machine.", demo: "openStems demo", demoText: "The demo shows the real workflow: load material, run separation and work with the resulting tracks from a single interface.", local: "Privacy by design", localText: "Audio does not need to leave the machine. Local processing removes external-service dependency and keeps material under control.", model: "Separation with Demucs", modelText: "The engine uses music source separation to extract vocals, drums, bass and other editable components.", workflow: "From file to stems", workflowText: "openStems combines preparation, separation, audition and management in one flow for musicians, producers and research.", youtube: "Watch directly on YouTube", next: "Explore more projects" },
  de: { back: "Zurück zum Portfolio", badge: "Lokale KI · Audiotrennung · Demucs", intro: "Eine Plattform zum Trennen, Abhören und Verwalten musikalischer Stems mit vollständig lokal ausgeführter KI.", demo: "openStems-Demo", demoText: "Die Demo zeigt den echten Ablauf: Material laden, Trennung ausführen und die resultierenden Spuren in einer Oberfläche bearbeiten.", local: "Datenschutz im Design", localText: "Audio muss den Rechner nicht verlassen. Lokale Verarbeitung vermeidet externe Dienste und hält das Material unter Kontrolle.", model: "Trennung mit Demucs", modelText: "Die Engine trennt Gesang, Schlagzeug, Bass und weitere editierbare Komponenten.", workflow: "Von der Datei zu den Stems", workflowText: "openStems verbindet Vorbereitung, Trennung, Vorhören und Verwaltung für Musiker, Produzenten und Forschung.", youtube: "Direkt auf YouTube ansehen", next: "Weitere Projekte" },
  fr: { back: "Retour au portfolio", badge: "IA locale · Séparation audio · Demucs", intro: "Une plateforme pour séparer, écouter et gérer des stems musicaux grâce à une IA exécutée entièrement en local.", demo: "Démo openStems", demoText: "La démonstration présente le flux réel : charger le contenu, lancer la séparation et travailler avec les pistes obtenues dans une seule interface.", local: "Confidentialité intégrée", localText: "L'audio n'a pas besoin de quitter la machine. Le traitement local évite les services externes et garde le contenu sous contrôle.", model: "Séparation avec Demucs", modelText: "Le moteur extrait voix, batterie, basse et autres composants éditables.", workflow: "Du fichier aux stems", workflowText: "openStems réunit préparation, séparation, préécoute et gestion pour musiciens, producteurs et recherche.", youtube: "Voir directement sur YouTube", next: "Explorer d'autres projets" },
};

export function OpenStemsProject() {
  const { language } = useLanguage();
  const t = copy[language];
  const cards = [{ icon: CloudOff, title: t.local, text: t.localText }, { icon: BrainCircuit, title: t.model, text: t.modelText }, { icon: Layers3, title: t.workflow, text: t.workflowText }];
  return <article className="py-24 lg:py-32 px-4 pt-32 relative overflow-hidden"><div className="max-w-5xl mx-auto">
    <Link href="/#portfolio" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8"><ArrowRight size={14} className="rotate-180" /> {t.back}</Link>
    <header className="mb-12"><span className="inline-flex px-4 py-2 rounded-full border border-emerald-400/20 bg-emerald-400/5 text-emerald-400 text-xs font-semibold tracking-widest uppercase mb-6">{t.badge}</span><h1 className="font-display text-5xl md:text-7xl font-bold tracking-tighter mb-6 gradient-text-animated">openStems</h1><p className="text-lg md:text-xl text-muted-foreground max-w-3xl leading-relaxed">{t.intro}</p></header>
    <section className="mb-16"><div className="relative aspect-video overflow-hidden rounded-3xl border border-border/50 bg-black elevation-3"><iframe className="absolute inset-0 w-full h-full" src="https://www.youtube-nocookie.com/embed/_5ZUFD1iu-g" title={t.demo} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="flex flex-col md:flex-row gap-5 justify-between mt-5"><div><h2 className="font-display text-2xl font-bold mb-2">{t.demo}</h2><p className="text-muted-foreground max-w-2xl leading-relaxed">{t.demoText}</p></div><a href="https://www.youtube.com/watch?v=_5ZUFD1iu-g" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-primary whitespace-nowrap">{t.youtube} <ArrowUpRight size={16} /></a></div></section>
    <section className="grid md:grid-cols-3 gap-5 mb-16">{cards.map(({ icon: Icon, title, text }) => <div key={title} className="p-7 rounded-2xl border border-border/50 bg-card/30"><Icon className="text-emerald-400 mb-5" /><h2 className="font-display text-xl font-bold mb-3">{title}</h2><p className="text-sm text-muted-foreground leading-relaxed">{text}</p></div>)}</section>
    <Link href="/#portfolio" className="inline-flex items-center gap-2 px-7 py-3.5 rounded-full bg-primary text-primary-foreground font-semibold">{t.next} <ArrowRight size={17} /></Link>
  </div></article>;
}
