import type { Language } from "@/lib/translations";
import type { Metadata } from "next";

export const pluginDownload = "/downloads/CELESTE-Parallel-VST3-Windows-v0.1.zip";
export const pluginImage = "/plugins/celeste-parallel/interface.png";
export const pluginSha256 = "3bcb629eaac46561bb9c7f09ab03cd2b55fd64f0ebb24f01e9c92c9eb05c1d3d";
export const pluginCopy = {
  es: {
    intro: "Instrumentos y efectos del laboratorio, ahora en tu estudio.", title: "Una fuente. Muchas texturas.",
    summary: "CELESTE Parallel lleva los delays, el wavefolder y la modulación a un efecto estéreo nativo para tu DAW. Gratis para Windows x64, sin FPGA ni navegador.",
    download: "Descarga gratuita", explore: "Historia y documentación", storyTitle: "De la placa al plugin",
    story: ["CELESTE empezó explorando una idea sobre la Tang Nano 20K: enviar una fuente de audio por distintas ramas y volver a reunirlas. El editor web permitió ver las conexiones; la FPGA, escuchar cómo cambiaba la señal al recorrerlas.", "Parallel v0.1 lleva esa idea al estudio. El procesamiento pasa a la CPU del ordenador y se integra en una pista del DAW. Delay A, Delay B y Wavefolder → Filter construyen capas de una misma fuente; Motion anima la mezcla y Space prolonga sus colas. La identidad visual sigue mostrando el recorrido del sonido.", "Es una primera versión concreta: cinco presets, rutas fijas y un cambio entre delays paralelos o en serie. La captura muestra el preset Neon Dust en el editor. El proyecto de hardware continúa por separado; este plugin no necesita la placa."],
    install: "Instalación en Windows", steps: ["Descarga y descomprime el ZIP.", "Copia la carpeta completa CELESTE Parallel.vst3, conservando Contents, en la ruta indicada debajo. Windows puede pedir permisos de administrador.", "Abre tu DAW, vuelve a escanear los plugins e inserta CELESTE Parallel como efecto en una pista estéreo con audio.", "Reproduce la pista, elige un preset y ajusta Master Mix. Compara con BYPASS. También se incluye una aplicación independiente para probar con entrada y salida de audio."],
    controls: "Guía de controles", controlText: ["Delay A / B: 20–1200 ms y 20–1600 ms. Feedback compartido hasta 85%. SERIES A → B encadena los delays; desactivado, funcionan en paralelo.", "Wavefolder: plegado de onda con sobremuestreo 2×. Filter: paso bajo de esta rama entre 80 Hz y 18 kHz.", "Space: reverberación estéreo. Motion: modulación del filtro y de la amplitud. LFO Rate: 0,05–8 Hz, sin sincronía BPM.", "Master Mix: mezcla original/procesada. Output: ganancia final. BYPASS devuelve la señal a ganancia unidad.", "Doble clic restaura un mando. Las casillas permiten escribir valores; el DAW puede automatizar parámetros y guardar el estado en la sesión."],
    demo: "Escucha el plugin", demoText: "Demo de 54 segundos renderizada con el VST3 y el preset Celestial Bloom, con cola y fundido final.",
    scope: "Qué incluye v0.1", scopeText: "Efecto estéreo VST3 de 64 bits para Windows, aplicación independiente, cinco presets, código fuente, demo, documentación y registros de pruebas. Necesita audio de entrada: no es un sintetizador. Sin versión macOS, entrada mono, editor libre de cables, Glitch, Chaos ni control de hardware en esta entrega.",
    tests: "Pruebas y alcance", testsText: "El paquete documenta pruebas DSP y carga del VST3 con Pedalboard a 44,1, 48 y 96 kHz, bypass, cambios de ruta y guardado de estado. No se afirma compatibilidad universal con todos los DAW ni validación prolongada en directo.",
    files: "Documentos del paquete (español)", readme: "Guía original", validation: "Registro de pruebas", hardware: "Explorar CELESTE en FPGA", back: "Todos los plugins", imageAlt: "Editor de CELESTE Parallel v0.1 con el preset Neon Dust, rutas y ocho controles", size: "ZIP · 25,8 MB · Windows x64 · v0.1",
  },
  ca: {
    intro: "Instruments i efectes del laboratori, ara al teu estudi.", title: "Una font. Moltes textures.",
    summary: "CELESTE Parallel porta els delays, el wavefolder i la modulació a un efecte estèreo natiu per al teu DAW. Gratuït per a Windows x64, sense FPGA ni navegador.",
    download: "Descàrrega gratuïta", explore: "Història i documentació", storyTitle: "De la placa al plugin",
    story: ["CELESTE va començar explorant una idea sobre la Tang Nano 20K: enviar una font d’àudio per diverses branques i reunir-les de nou. L’editor web permetia veure les connexions; l’FPGA, escoltar com canviava el senyal.", "Parallel v0.1 porta aquesta idea a l’estudi. La CPU de l’ordinador processa l’àudio dins d’una pista del DAW. Delay A, Delay B i Wavefolder → Filter creen capes d’una mateixa font; Motion anima la mescla i Space n’allarga les cues. La interfície continua mostrant el recorregut del so.", "És una primera versió amb cinc presets, rutes fixes i delays en paral·lel o en sèrie. La captura mostra Neon Dust a l’editor. El projecte de hardware continua per separat; el plugin no necessita la placa."],
    install: "Instal·lació a Windows", steps: ["Descarrega i descomprimeix el ZIP.", "Copia tota la carpeta CELESTE Parallel.vst3, conservant Contents, a la ruta de sota. Windows pot demanar permisos d’administrador.", "Obre el DAW, torna a escanejar els plugins i insereix CELESTE Parallel com a efecte en una pista estèreo amb àudio.", "Reprodueix la pista, tria un preset i ajusta Master Mix. Compara amb BYPASS. També s’inclou una aplicació independent per provar amb entrada i sortida d’àudio."],
    controls: "Guia dels controls", controlText: ["Delay A / B: 20–1200 ms i 20–1600 ms. Feedback compartit fins al 85%. SERIES A → B encadena els delays; desactivat, treballen en paral·lel.", "Wavefolder: plegat d’ona amb sobremostreig 2×. Filter: passa-baix d’aquesta branca entre 80 Hz i 18 kHz.", "Space: reverberació estèreo. Motion: modulació del filtre i l’amplitud. LFO Rate: 0,05–8 Hz, sense sincronització BPM.", "Master Mix: mescla original/processada. Output: guany final. BYPASS retorna el senyal a guany unitari.", "Doble clic restaura un control. Pots escriure valors, automatitzar paràmetres al DAW i desar l’estat a la sessió."],
    demo: "Escolta el plugin", demoText: "Demo de 54 segons renderitzada amb el VST3 i el preset Celestial Bloom, amb cua i esvaïment final.",
    scope: "Què inclou v0.1", scopeText: "Efecte estèreo VST3 de 64 bits per a Windows, aplicació independent, cinc presets, codi font, demo, documentació i registres de proves. Necessita àudio d’entrada: no és un sintetitzador. Aquesta versió no inclou macOS, entrada mono, editor lliure de cables, Glitch, Chaos ni control de hardware.",
    tests: "Proves i abast", testsText: "El paquet documenta proves DSP i càrrega del VST3 amb Pedalboard a 44,1, 48 i 96 kHz, bypass, canvis de ruta i desament d’estat. No s’afirma compatibilitat universal amb tots els DAW ni validació prolongada en directe.",
    files: "Documents del paquet (castellà)", readme: "Guia original", validation: "Registre de proves", hardware: "Explorar CELESTE en FPGA", back: "Tots els plugins", imageAlt: "Editor de CELESTE Parallel v0.1 amb el preset Neon Dust, rutes i vuit controls", size: "ZIP · 25,8 MB · Windows x64 · v0.1",
  },
  en: {
    intro: "Instruments and effects from the lab, now in your studio.", title: "One source. Many textures.",
    summary: "CELESTE Parallel brings delays, wavefolding and modulation into a native stereo effect for your DAW. Free for Windows x64, with no FPGA or browser required.",
    download: "Free download", explore: "Story and documentation", storyTitle: "From the board to the plugin",
    story: ["CELESTE began with an idea on the Tang Nano 20K: send one audio source through several branches, then bring them together again. The web editor made the connections visible; the FPGA made their effect on the signal audible.", "Parallel v0.1 brings that idea into the studio. Processing moves to the computer’s CPU, inside a DAW track. Delay A, Delay B and Wavefolder → Filter build layers from a single source; Motion animates the mix and Space extends its tails. The interface still reveals the path of the sound.", "This first release has five presets, fixed routing and parallel or serial delays. The screenshot shows Neon Dust in the editor. The hardware project continues separately; the plugin does not need the board."],
    install: "Windows installation", steps: ["Download and extract the ZIP.", "Copy the entire CELESTE Parallel.vst3 folder, keeping Contents intact, to the path below. Windows may request administrator permission.", "Open your DAW, rescan plugins and insert CELESTE Parallel as an effect on a stereo track containing audio.", "Play the track, choose a preset and adjust Master Mix. Compare with BYPASS. A standalone application is also included for testing with an audio input and output."],
    controls: "Control guide", controlText: ["Delay A / B: 20–1200 ms and 20–1600 ms. Shared feedback up to 85%. SERIES A → B chains the delays; when off, they run in parallel.", "Wavefolder: wavefolding with 2× oversampling. Filter: a low-pass filter on this branch, from 80 Hz to 18 kHz.", "Space: stereo reverb. Motion: filter and amplitude modulation. LFO Rate: 0.05–8 Hz, without BPM sync.", "Master Mix: dry/wet balance. Output: final gain. BYPASS returns the signal at unity gain.", "Double-click resets a knob. Enter values in the fields, automate parameters in your DAW and save the state in your session."],
    demo: "Hear the plugin", demoText: "A 54-second demo rendered through the VST3 using Celestial Bloom, including its tail and a final fade.",
    scope: "What v0.1 includes", scopeText: "A Windows 64-bit stereo VST3 effect, standalone app, five presets, source code, demo, documentation and test logs. Audio input is required: this is not a synthesizer. This release has no macOS binary, mono input, free cable editor, Glitch, Chaos or hardware control.",
    tests: "Testing and scope", testsText: "The package documents DSP and VST3 loading tests with Pedalboard at 44.1, 48 and 96 kHz, bypass, routing changes and state persistence. It does not claim compatibility with every DAW or prolonged live validation.",
    files: "Package documents (Spanish)", readme: "Original guide", validation: "Test record", hardware: "Explore CELESTE on FPGA", back: "All plugins", imageAlt: "CELESTE Parallel v0.1 editor showing Neon Dust, signal paths and eight controls", size: "ZIP · 25.8 MB · Windows x64 · v0.1",
  },
  fr: {
    intro: "Instruments et effets du laboratoire, maintenant dans votre studio.", title: "Une source. Plusieurs textures.",
    summary: "CELESTE Parallel réunit delays, wavefolder et modulation dans un effet stéréo natif pour votre DAW. Gratuit pour Windows x64, sans FPGA ni navigateur.",
    download: "Téléchargement gratuit", explore: "Histoire et documentation", storyTitle: "De la carte au plugin",
    story: ["CELESTE est né d’une idée sur la Tang Nano 20K : envoyer une source audio dans plusieurs branches, puis les réunir. L’éditeur web rendait les connexions visibles ; le FPGA permettait d’entendre leur effet sur le signal.", "Parallel v0.1 apporte cette idée au studio. Le processeur de l’ordinateur traite le son dans une piste du DAW. Delay A, Delay B et Wavefolder → Filter superposent les textures ; Motion anime le mixage et Space prolonge les résonances. L’interface montre toujours le parcours du son.", "Cette première version propose cinq presets, des routes fixes et des delays en parallèle ou en série. La capture montre Neon Dust dans l’éditeur. Le projet matériel continue séparément ; le plugin ne nécessite pas la carte."],
    install: "Installation sous Windows", steps: ["Téléchargez et décompressez le ZIP.", "Copiez tout le dossier CELESTE Parallel.vst3, en conservant Contents, dans le chemin ci-dessous. Windows peut demander des droits administrateur.", "Ouvrez votre DAW, relancez la recherche de plugins et insérez CELESTE Parallel comme effet sur une piste stéréo contenant de l’audio.", "Lancez la lecture, choisissez un preset et ajustez Master Mix. Comparez avec BYPASS. Une application autonome est également fournie pour tester une entrée et une sortie audio."],
    controls: "Guide des commandes", controlText: ["Delay A / B : 20–1200 ms et 20–1600 ms. Feedback partagé jusqu’à 85 %. SERIES A → B met les delays en cascade ; désactivé, ils fonctionnent en parallèle.", "Wavefolder : repliement d’onde avec suréchantillonnage 2×. Filter : passe-bas de cette branche, de 80 Hz à 18 kHz.", "Space : réverbération stéréo. Motion : modulation du filtre et de l’amplitude. LFO Rate : 0,05–8 Hz, sans synchronisation BPM.", "Master Mix : équilibre original/traité. Output : gain final. BYPASS restitue le signal à gain unitaire.", "Un double-clic réinitialise une commande. Saisissez des valeurs, automatisez les paramètres dans le DAW et sauvegardez l’état dans la session."],
    demo: "Écouter le plugin", demoText: "Demo de 54 secondes rendue par le VST3 avec Celestial Bloom, avec résonance et fondu final.",
    scope: "Contenu de v0.1", scopeText: "Effet stéréo VST3 64 bits pour Windows, application autonome, cinq presets, code source, demo, documentation et journaux de tests. Une entrée audio est nécessaire : ce n’est pas un synthétiseur. Cette version n’inclut ni macOS, ni entrée mono, ni câblage libre, ni Glitch, Chaos ou contrôle matériel.",
    tests: "Tests et portée", testsText: "Le paquet documente les tests DSP et le chargement VST3 avec Pedalboard à 44,1, 48 et 96 kHz, le bypass, les changements de routage et la sauvegarde d’état. Aucune compatibilité universelle avec les DAW ni validation prolongée en concert n’est revendiquée.",
    files: "Documents du paquet (espagnol)", readme: "Guide original", validation: "Rapport de tests", hardware: "Explorer CELESTE sur FPGA", back: "Tous les plugins", imageAlt: "Éditeur CELESTE Parallel v0.1 avec Neon Dust, routage et huit commandes", size: "ZIP · 25,8 Mo · Windows x64 · v0.1",
  },
  de: {
    intro: "Instrumente und Effekte aus dem Labor, jetzt in deinem Studio.", title: "Eine Quelle. Viele Texturen.",
    summary: "CELESTE Parallel bringt Delays, Wavefolding und Modulation als nativen Stereo-Effekt in deine DAW. Kostenlos für Windows x64, ohne FPGA oder Browser.",
    download: "Kostenlos herunterladen", explore: "Geschichte und Dokumentation", storyTitle: "Von der Platine zum Plugin",
    story: ["CELESTE begann mit einer Idee auf dem Tang Nano 20K: eine Audioquelle durch mehrere Zweige schicken und wieder zusammenführen. Der Web-Editor machte die Verbindungen sichtbar; das FPGA machte ihre Wirkung hörbar.", "Parallel v0.1 bringt diese Idee ins Studio. Die CPU des Computers verarbeitet das Signal in einer DAW-Spur. Delay A, Delay B und Wavefolder → Filter erzeugen Schichten derselben Quelle; Motion bewegt die Mischung und Space verlängert den Nachklang. Die Oberfläche zeigt weiterhin den Weg des Klangs.", "Diese erste Version enthält fünf Presets, feste Signalwege und parallele oder serielle Delays. Das Bild zeigt Neon Dust im Editor. Das Hardwareprojekt läuft separat weiter; das Plugin benötigt keine Platine."],
    install: "Installation unter Windows", steps: ["ZIP herunterladen und entpacken.", "Den vollständigen Ordner CELESTE Parallel.vst3 einschließlich Contents in den unten angegebenen Pfad kopieren. Windows kann Administratorrechte anfordern.", "DAW öffnen, Plugins neu einlesen und CELESTE Parallel als Effekt auf einer Stereospur mit Audio einsetzen.", "Spur abspielen, Preset wählen und Master Mix einstellen. Mit BYPASS vergleichen. Eine eigenständige Anwendung für Tests mit Audioein- und -ausgang liegt ebenfalls bei."],
    controls: "Bedienung", controlText: ["Delay A / B: 20–1200 ms und 20–1600 ms. Gemeinsames Feedback bis 85 %. SERIES A → B schaltet die Delays hintereinander; ausgeschaltet laufen sie parallel.", "Wavefolder: Wellenfaltung mit 2× Oversampling. Filter: Tiefpass dieses Zweigs von 80 Hz bis 18 kHz.", "Space: Stereo-Hall. Motion: Filter- und Amplitudenmodulation. LFO Rate: 0,05–8 Hz, ohne BPM-Synchronisierung.", "Master Mix: Verhältnis von Original und Effektsignal. Output: Ausgangspegel. BYPASS gibt das Signal mit Verstärkung eins aus.", "Doppelklick setzt einen Regler zurück. Werte lassen sich eingeben, Parameter in der DAW automatisieren und Einstellungen in der Session speichern."],
    demo: "Plugin anhören", demoText: "54 Sekunden Demo, mit dem VST3 und Celestial Bloom gerendert, einschließlich Nachklang und Ausblendung.",
    scope: "Inhalt von v0.1", scopeText: "Stereo-VST3-Effekt für Windows 64 Bit, eigenständige Anwendung, fünf Presets, Quellcode, Demo, Dokumentation und Testprotokolle. Audioeingang erforderlich: kein Synthesizer. Diese Version enthält keine macOS-Datei, keinen Monoeingang, keine freie Verkabelung, kein Glitch, Chaos oder Hardwaresteuerung.",
    tests: "Tests und Umfang", testsText: "Das Paket dokumentiert DSP-Tests und VST3-Laden mit Pedalboard bei 44,1, 48 und 96 kHz, Bypass, Routingwechsel und Zustandsspeicherung. Eine Kompatibilität mit jeder DAW oder ausgedehnte Live-Tests werden nicht behauptet.",
    files: "Paketdokumente (Spanisch)", readme: "Originalanleitung", validation: "Testprotokoll", hardware: "CELESTE auf FPGA entdecken", back: "Alle Plugins", imageAlt: "CELESTE Parallel v0.1 mit Neon Dust, Signalwegen und acht Reglern", size: "ZIP · 25,8 MB · Windows x64 · v0.1",
  },
} satisfies Record<Language, object>;

export function pluginMetadata(language: Language, path = "/plugins/celeste-parallel"): Metadata {
  const copy = pluginCopy[language];
  const title = path === "/plugins" ? "Plugins | Cesco.dev" : "CELESTE Parallel · VST3 v0.1 | Cesco.dev";
  return { title, description: copy.summary, alternates: { canonical: `https://cesco.dev${path}` }, openGraph: { title, description: copy.summary, url: `https://cesco.dev${path}`, images: [{ url: pluginImage, alt: copy.imageAlt }] }, twitter: { card: "summary_large_image", title, description: copy.summary, images: [pluginImage] } };
}
